### ISSUE TITLE
Error on login via JS call

### ISSUE THREAD

**Issue by taier** [spiir/nag-example-apps#1]
[On this line ](https://github.com/spiir/nag-example-apps/blob/8489db84ca612e30965e7332ac58bbbee017415d/ios/QuickSprout/QuickSprout/Framework/NAGLoginView.swift#L106) fails with error: 
<img width="631" alt="screen shot 2018-11-05 at 8 57 30 pm" src="https://user-images.githubusercontent.com/3410310/48022344-9560af00-e143-11e8-9e7d-5827d7843da4.png">

**Comment by bvdspiir** [comment]
I added a check to the framework to ensure that data is not null.
