### ISSUE TITLE
Building for iOS failed with error - multi architecture framework is not now supported 

### ISSUE THREAD

**Issue by sevriugin** [spiir/nag-example-apps#20]
Hi, guys, it looks like to due to migration process to new chip Apple now forbid to include in one library several architectures. So, please update example app if possible because now is not build with error: 

Building for iOS Simulator, but the linked and embedded framework 'NAGLoginSDK.framework' was built for iOS + iOS Simulator.

**Comment by jayj** [comment]
Hi @sevriugin 

Does it work for you if to try to use the Framework file from https://github.com/spiir/nag-example-apps/pull/21 ?

**Comment by sevriugin** [comment]
Hi, @jayj , yes it's building now, issue is resolved, thanks
